# Generated by Django 4.1 on 2022-08-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_liked_article_updated_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
